org: layonez
app: vaccination-handbook-api-app
service: vaccination-handbook-api-app

frameworkVersion: "2"

custom:
  vaccinesTableName: "vaccines-table-${self:provider.stage}"
  infectionsTableName: "infections-table-${self:provider.stage}"
  restrictionsTableName: "restrictions-table-${self:provider.stage}"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [VaccinesTable, Arn]
            - Fn::GetAtt: [InfectionsTable, Arn]
            - Fn::GetAtt: [RestrictionsTable, Arn]
  environment:
    VACCINES_TABLE: ${self:custom.vaccinesTableName}
    INFECTIONS_TABLE: ${self:custom.infectionsTableName}
    RESTRICTIONS_TABLE: ${self:custom.restrictionsTableName}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    VaccinesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.vaccinesTableName}
    InfectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.infectionsTableName}
    RestrictionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.restrictionsTableName}
